### ISSUE TITLE
请问怎么做成接口调用？

### ISSUE THREAD

**Issue by yumath** [zjy-ucas/ChineseNER#36]
我好像绕不过tf.app.run()这个坎，没有办法做一个接口，调用main中的实体识别功能

**Comment by ghost** [comment]
在一个session里面，不停读消息然后调用evaluate()就行了
读消息的方法很多，可以和数据库通信，可以共享内存，可以直接处理http请求
看哪种合适就用哪种咯

**Comment by ares89** [comment]
模型保存后使用java读取后调用

**Comment by yumath** [comment]
谢谢大家的解答，可能我没有表述清楚。

我遇到的问题是：在main.py中的evaluate_line()中为什么不能return呢？

**Comment by yumath** [comment]
我解决了这个问题，在这里做个记录，大家也是互相学习。

不知道为什么在with语句之后，无法执行return语句，导致evaluate_line无法返回。
后来删除了with语句，改用`sess = tf.Session(config=tf_config)`就可以了

**Comment by xingyuezhiji** [comment]
在with tf.session 前面加一句 tf.reset_default_graph() 我是这么解决的

**Comment by chaotianjiao** [comment]
题主在吗？我改成sess = tf.Session(config=tf_config) 后 又报错ValueError: Cannot evaluate tensor using `eval()`:，请问一下这个有解决办法吗？ tf.reset_default_graph() 确实可以解决，但是好像每次都要重新创建模型，运行时间有点久

**Comment by yumath** [comment]
> 题主在吗？我改成sess = tf.Session(config=tf_config) 后 又报错ValueError: Cannot evaluate tensor using `eval()`:，请问一下这个有解决办法吗？ tf.reset_default_graph() 确实可以解决，但是好像每次都要重新创建模型，运行时间有点久

把session作为参数传给eval

**Comment by chaotianjiao** [comment]
> > 题主在吗？我改成sess = tf.Session(config=tf_config) 后 又报错ValueError: Cannot evaluate tensor using `eval()`:，请问一下这个有解决办法吗？ tf.reset_default_graph() 确实可以解决，但是好像每次都要重新创建模型，运行时间有点久
> 
> 把session作为参数传给eval

大佬能在具体点吗？是result = model.evaluate_line哪里修改吗还是怎样修改啊？
最后一句是return result

**Comment by yumath** [comment]
@chaotianjiao 把model类内函数evaluate_line():的第一行改为trans = self.trans.eval(sess)

**Comment by chaotianjiao** [comment]
> @chaotianjiao 把model类内函数evaluate_line():的第一行改为trans = self.trans.eval(sess)

感谢大佬，已经修改了，第一次能成功调用，但是多次同时多次调用就又会报错ValueError: Variable char_embedding/char_embedding already exists, disallowed. 大佬能顺便再指导一下吗？

**Comment by yumath** [comment]
@chaotianjiao 这个具体我就不清楚了，你自己debug一下吧
