### ISSUE TITLE
损失函数

### ISSUE THREAD

**Issue by zgd716** [zjy-ucas/ChineseNER#55]
大佬们，请问一下损失函数start_logits /pad_logits作用是什么？而且我看网上转移矩阵不是加了start/end两个嘛，为什么代码里是+1而不是+2

**Comment by ShangzhiH** [comment]
原作者没有实现end的paddding，可以看这个讨论 https://github.com/zjy-ucas/ChineseNER/issues/10 里面有人贴了start和end的padding

**Comment by zgd716** [comment]
> 原作者没有实现end的paddding，可以看这个讨论 #10 里面有人贴了start和end的padding

好的，多谢了
