### ISSUE TITLE
求助，这个报错是什么原因，用的自己的数据和删除部分自带的训练数据后都会有该错误

### ISSUE THREAD

**Issue by Zhenguoshen** [zjy-ucas/ChineseNER#82]
File "D:\nlp\ChineseNER\loader.py", line 110, in <listcomp>
    tags = [tag_to_id[w[-1]] for w in s]

KeyError: 'S-ORG'

**Comment by Zhenguoshen** [comment]
问题已经解决

**Comment by touchankawaii** [comment]
你好请问你是怎么解决的，我也遇到了这个问题

**Comment by ghost** [comment]
> File "D:\nlp\ChineseNER\loader.py", line 110, in
> tags = [tag_to_id[w[-1]] for w in s]
> 
> KeyError: 'S-ORG'

你好请问你是怎么解决的，我也遇到了这个问题
